In [1]:
import torch
from tensordict import TensorDict

ds = TensorDict(
    {
        'input_ids':torch.randn((2,5)),
    }
)
ds



TensorDict(
    fields={
        input_ids: Tensor(shape=torch.Size([2, 5]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([]),
    device=None,
    is_shared=False)

In [25]:
import torch
import numpy as np

mob3d30  = 1
xgb = 0.6
#pred = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.]
pred = [0.43,0.44,0.45,0.46,0.47,0.48,0.49,0.50,0.51,0.52]

reward_xgb = 1 - 2*(np.array(pred) - xgb) ** 2 # [-1,1]
reward_mob3d30 = 1 - 2*(np.array(pred) - mob3d30) ** 2 # [-1,1]

reward_xgb,reward_mob3d30

(array([0.9968, 0.9982, 0.9992, 0.9998, 1.    , 0.9998, 0.9992, 0.9982,
        0.9968, 0.995 ]),
 array([0.3502, 0.3728, 0.395 , 0.4168, 0.4382, 0.4592, 0.4798, 0.5   ,
        0.5198, 0.5392]))

In [26]:
reward = 0.5 * reward_xgb + 0.5 * reward_mob3d30
reward

array([0.6735, 0.6855, 0.6971, 0.7083, 0.7191, 0.7295, 0.7395, 0.7491,
       0.7583, 0.7671])

In [27]:
reward_mean = np.mean(reward)
reward_std = np.std(reward)
adv = (reward - reward_mean) / (reward_std + 1e-8)
adv

array([-1.64509618, -1.24385321, -0.855985  , -0.48149156, -0.12037289,
        0.22737102,  0.56174016,  0.88273453,  1.19035414,  1.48459899])

In [28]:
reward_xgb_mean = np.mean(reward_xgb)
reward_xgb_std = np.std(reward_xgb)
adv_xgb = (reward_xgb - reward_xgb_mean) / (reward_xgb_std + 1e-8)
adv_xgb

array([-0.95987714, -0.06399181,  0.57592629,  0.95987714,  1.08786076,
        0.95987714,  0.57592629, -0.06399181, -0.95987714, -2.11172971])

In [29]:
reward_mob3d30_mean = np.mean(reward_mob3d30)
reward_mob3d30_std = np.std(reward_mob3d30)
adv_mob3d30 = (reward_mob3d30 - reward_mob3d30_mean) / (reward_mob3d30_std + 1e-8)
adv_mob3d30

array([-1.60602174, -1.23144907, -0.86350601, -0.50219256, -0.1475087 ,
        0.20054554,  0.54197018,  0.87676522,  1.20493065,  1.52646648])

In [30]:
adv_combined = 0.5 * adv_xgb + 0.5 * adv_mob3d30
adv_combined

array([-1.28294944, -0.64772044, -0.14378986,  0.22884229,  0.47017603,
        0.58021134,  0.55894823,  0.40638671,  0.12252675, -0.29263162])